DATA : 
   ACOUNT_DATABASE : hugomathien/soccer
   DATABASE_URL : /home/ali/Desktop/EuroFootballClustering/data/database.sqlite

QUERY : 
   PLAYER_QUERY : select * from  Player p  join Player_Attributes pa on p.player_api_id== pa.player_api_id;
   TEAM_QUERY : select * from Team t join Team_Attributes ta on t.team_api_id == ta.team_api_id;
   COUNTRY_QUERY : select * from  League l  join Country c on l.country_id== c.id;
   MATCH_QUERY : select * from Match ;

COLUMNS:
   DROP_PLAYER : ['player_fifa_api_id','player_api_id']
   DROP_TEAM :  ['team_fifa_api_id']
   DROP_COUNTRY: ['country_id']
   DROP_MATCH : ['league_id','home_player_X1', 'home_player_X2', 'home_player_X3', 'home_player_X4', 'home_player_X5', 'home_player_X6', 'home_player_X7', 'home_player_X8', 'home_player_X9', 'home_player_X10', 'home_player_X11', 'away_player_X1', 'away_player_X2', 'away_player_X3', 'away_player_X4', 'away_player_X5', 'away_player_X6', 'away_player_X7', 'away_player_X8', 'away_player_X9', 'away_player_X10', 'away_player_X11', 'home_player_Y1', 'home_player_Y2', 'home_player_Y3', 'home_player_Y4', 'home_player_Y5', 'home_player_Y6', 'home_player_Y7', 'home_player_Y8', 'home_player_Y9', 'home_player_Y10', 'home_player_Y11', 'away_player_Y1', 'away_player_Y2', 'away_player_Y3', 'away_player_Y4', 'away_player_Y5', 'away_player_Y6', 'away_player_Y7', 'away_player_Y8', 'away_player_Y9', 'away_player_Y10', 'away_player_Y11','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA']
   
   # use in the general analyse to only keep this column(but it might be better to keep column so you can see the attribute)
   KEEP_PLAYER : ['player_name', 'overall_rating', 'potential', 'season']
   KEEP_TEAM : ['team_long_name', 'team_short_name', 'buildUpPlaySpeed', 'buildUpPlayPassing', 'buildUpPlayPositioningClass', 'chanceCreationPassing', 'chanceCreationCrossing', 'chanceCreationShooting', 'defencePressure', 'defenceAggression', 'defenceTeamWidth']
   KEEP_MATCH : ['league_name', 'country_name', 'season', 'home_team', 'away_team', 'home_team_goal', 'away_team_goal']
   

   CLUSTER_PLAYER : ['overall_rating', 'potential', 'height', 'weight', 'preferred_foot', 'attacking_work_rate', 'positioning','penalties', 'finishing', 'crossing', 'short_passing', 'long_passing', 'shot_power', 'aggression', 'free_kick_accuracy', 'defensive_work_rate']
   CLUSTER_TEAM: [ 'buildUpPlaySpeed', 'buildUpPlaySpeedClass', 'buildUpPlayDribblingClass', 'buildUpPlayPassing', 'buildUpPlayPassingClass', 'chanceCreationPassing', 'chanceCreationPassingClass', 'chanceCreationCrossing', 'chanceCreationCrossingClass', 'chanceCreationShooting', 'chanceCreationShootingClass', 'defencePressure', 'defencePressureClass', 'defenceAggression', 'defenceAggressionClass', 'defenceDefenderLineClass']

  # CLUSTER_PLAYER : ['overall_rating', 'potential', 'height', 'weight', 'preferred_foot', 'attacking_work_rate', 'positioning','penalties', 'finishing', 'crossing', 'short_passing', 'long_passing', 'shot_power', 'aggression', 'free_kick_accuracy', 'defensive_work_rate']






         